# typed: false
# frozen_string_literal: true

# Homebrew formula for the straas CLI.
# Generated by scripts/release.sh — do not edit manually.
class Straas < Formula
  desc "Squad-driven workspace CLI for Claude-based development environments"
  homepage "https://github.com/straas-tech/homebrew-tap"
  version "0.2.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/straas-tech/install/releases/download/v0.2.0/straas_darwin_arm64.tar.gz"
      sha256 "20d33b202393268c8bd0cd2f10896420eed8a5909d39552070369f92bf824de9"
    end

    on_intel do
      url "https://github.com/straas-tech/install/releases/download/v0.2.0/straas_darwin_amd64.tar.gz"
      sha256 "7250e78d829367f4b0017f3651cd11742149293b97a76c4195f740c5a321d118"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/straas-tech/install/releases/download/v0.2.0/straas_linux_arm64.tar.gz"
      sha256 "5d4237becbab68bf40f4257798aae2e64a5c60eb8d7fa72720b4be136a91efc4"
    end

    on_intel do
      url "https://github.com/straas-tech/install/releases/download/v0.2.0/straas_linux_amd64.tar.gz"
      sha256 "ea0287a8505a5f29a0511d7c07a20329fd0643eab1ef0f95a2d51eec29b0956e"
    end
  end

  def install
    bin.install "straas"
  end

  test do
    system bin/"straas", "--version"
  end
end
