# typed: false
# frozen_string_literal: true

# Homebrew formula for the straas CLI.
# Generated by scripts/release.sh — do not edit manually.
class Straas < Formula
  desc "Squad-driven workspace CLI for Claude-based development environments"
  homepage "https://github.com/straas-tech/homebrew-tap"
  version "0.12.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/straas-tech/install/releases/download/v0.12.2/straas_darwin_arm64.tar.gz"
      sha256 "d44ce5e7521ed66e5b1e098304ed5d798009dbe3f3e54f15e009d8bff7c3db84"
    end

    on_intel do
      url "https://github.com/straas-tech/install/releases/download/v0.12.2/straas_darwin_amd64.tar.gz"
      sha256 "6826896f9bb2c1b233992ddd091d94cec847901205f0ee12e2526f59a1107052"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/straas-tech/install/releases/download/v0.12.2/straas_linux_arm64.tar.gz"
      sha256 "96b7c64b4e415f25343dc238f28804056cd95a61398765aaec75285ba38cbcba"
    end

    on_intel do
      url "https://github.com/straas-tech/install/releases/download/v0.12.2/straas_linux_amd64.tar.gz"
      sha256 "c7376a100b79d1595ee8fc505cc32f06234597eb8eddcf1a34ef770694c6e2b1"
    end
  end

  def install
    bin.install "straas"
  end

  test do
    system bin/"straas", "--version"
  end
end
