# typed: false
# frozen_string_literal: true

# Homebrew formula for the straas CLI.
# Generated by scripts/release.sh — do not edit manually.
class Straas < Formula
  desc "Squad-driven workspace CLI for Claude-based development environments"
  homepage "https://github.com/straas-tech/homebrew-tap"
  version "0.7.3"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/straas-tech/install/releases/download/v0.7.3/straas_darwin_arm64.tar.gz"
      sha256 "0de29e6e0102763502bbf6568cbe0b33bd8e37fd9abc74e092f13b1dc4b04eea"
    end

    on_intel do
      url "https://github.com/straas-tech/install/releases/download/v0.7.3/straas_darwin_amd64.tar.gz"
      sha256 "c9ec46717d7481106591ea567453b0541f1ddd88b7a008cdcd3986ae1f56e4db"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/straas-tech/install/releases/download/v0.7.3/straas_linux_arm64.tar.gz"
      sha256 "5196dc412814577b4ac421aabb328d7ea24288290d84bcaafd31aa78655e91fd"
    end

    on_intel do
      url "https://github.com/straas-tech/install/releases/download/v0.7.3/straas_linux_amd64.tar.gz"
      sha256 "0478672e217fbc0788c80ff4a97a891c68e8bdd34babc0d319caa8775727cb8f"
    end
  end

  def install
    bin.install "straas"
  end

  test do
    system bin/"straas", "--version"
  end
end
